-- Sccsid:     @(#)dss.ri	2.1.8.1
-- TPCD Benchmark Version 8.0

-- ALTER TABLE region DROP PRIMARY KEY;
-- ALTER TABLE nation DROP PRIMARY KEY;
-- ALTER TABLE part DROP PRIMARY KEY;
-- ALTER TABLE supplier DROP PRIMARY KEY;
-- ALTER TABLE partsupp DROP PRIMARY KEY;
-- ALTER TABLE orders DROP PRIMARY KEY;
-- ALTER TABLE lineitem DROP PRIMARY KEY;
-- ALTER TABLE customer DROP PRIMARY KEY;


-- For table REGION
ALTER TABLE region
ADD PRIMARY KEY (R_REGIONKEY);

-- For table NATION
ALTER TABLE nation
ADD PRIMARY KEY (N_NATIONKEY);

ALTER TABLE nation
ADD FOREIGN KEY NATION_FK1 (N_REGIONKEY) references region(R_REGIONKEY);

-- For table PART
ALTER TABLE part
ADD PRIMARY KEY (P_PARTKEY);

-- For table SUPPLIER
ALTER TABLE supplier
ADD PRIMARY KEY (S_SUPPKEY);

ALTER TABLE supplier
ADD FOREIGN KEY SUPPLIER_FK1 (S_NATIONKEY) references nation(N_NATIONKEY);

-- For table PARTSUPP
ALTER TABLE partsupp
ADD PRIMARY KEY (PS_PARTKEY,PS_SUPPKEY);

-- For table CUSTOMER
ALTER TABLE customer
ADD PRIMARY KEY (C_CUSTKEY);

ALTER TABLE customer
ADD FOREIGN KEY CUSTOMER_FK1 (C_NATIONKEY) references nation(N_NATIONKEY);

-- For table LINEITEM
ALTER TABLE lineitem
ADD PRIMARY KEY (L_ORDERKEY,L_LINENUMBER);

-- For table ORDERS
ALTER TABLE orders
ADD PRIMARY KEY (O_ORDERKEY);

-- For table PARTSUPP
ALTER TABLE partsupp
ADD FOREIGN KEY PARTSUPP_FK1 (PS_SUPPKEY) references supplier(S_SUPPKEY);

ALTER TABLE partsupp
ADD FOREIGN KEY PARTSUPP_FK2 (PS_PARTKEY) references part(P_PARTKEY);

-- For table ORDERS
ALTER TABLE orders
ADD FOREIGN KEY ORDERS_FK1 (O_CUSTKEY) references customer(C_CUSTKEY);

-- For table LINEITEM
ALTER TABLE lineitem
ADD FOREIGN KEY LINEITEM_FK1 (L_ORDERKEY)  references orders(O_ORDERKEY);

ALTER TABLE lineitem
ADD FOREIGN KEY LINEITEM_FK2 (L_PARTKEY,L_SUPPKEY) references partsupp(PS_PARTKEY, PS_SUPPKEY);

